export const RIGHT_PRODUCT = 121000;
export const RIGHT_PRODUCT_DELETE = 121004;
export const RIGHT_PRODUCT_ADD = 121002;
export const RIGHT_PRODUCT_UPDATE = 121003;
export const RIGHT_PRODUCT_DUPLICATE = 121005;

export const PRICE_ORIGINS = ["PRICELIST", "PROVIDER", "RELATIVE"];
export const LIMIT_TYPES = ["FIXED_AMOUNT", "CO_INSURANCE"];

export const CEILING_DISCRIMINATION = ["HEALTH_FACILITY_TYPE", "CLAIM_TYPE"];

export const CEILING_EXCLUSIONS = ["HOSPITAL", "NON_HOSPITAL", "BOTH"];
export const CEILING_TYPES = ["TREATMENT", "POLICY", "INSUREE"];
